version: "3.3"

networks:
  local:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sanboxapp
    container_name: sanboxapp-madiun-kota
    restart: unless-stopped
    volumes: 
      - ./madiunkota:/code

  php:
    image: php:7.4-fpm
    container_name: php7.4-madiun-kota
    build:
      context: ./
    ports:
      - "9004:9000"
    volumes:
      - ./madiunkota:/code
    networks:
      - local

  nginx:
    image: nginx:1.21.3
    container_name: nginx1.21.3-madiun-kota
    ports:
      - "8084:80"
    volumes:
      - ./madiunkota:/code
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - local

  postgres_madiunkota:
    image: postgres:14
    container_name: postgres14-madiun-kota
    restart: unless-stopped
    tty: true
    environment:
      - POSTGRES_DB=madiunkota
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=M4d1iunK0t4
    logging:
      options:
        max-size: 1000m
        max-file: "3"
    ports:
      - '54324:5432'
    volumes: 
      - ./postgres-data-madiunkota:/var/lib/postgresql/data-madiunkota

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4-madiun-kota
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL: "berlinwibi@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "B3rl1N2021"
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - 54:5050
    depends_on:
      - postgres_madiunkota
    networks: 
      - local